### ISSUE TITLE
Change the background color of the status bar in the headline?

### ISSUE THREAD

**Issue by Flo-Wo** [benjamin-weiss/hsrmbeamertheme#3]
1) Is there a possibility to change the background color of the status bar, that shows all the sections and subsections? I can't find the position in the .sty file.

2) How can I remove the capitalization in the section pages and add the current subsection on the section pages (maybe both numbered and not numbered, if possible)?
`
% Make Sectionhead uppercase
\newcommand{\insertsectionHEAD}{%
	\expandafter\insertsectionHEADaux\insertsectionhead}
	\newcommand{\insertsectionHEADaux}[3]{\MakeUppercase{#3}}
`
Removing `{\MakeUppercase{#3}}` doesn't solve the problem.

Thank you very much.

**Comment by benjamin-weiss** [comment]
You really should not use this theme. There are definitely some issues with this theme I will never fix. Instead you should use [metropolis](https://github.com/matze/mtheme). It is much more mature and easier to customize. If there is something I'm doing in my theme you prefer and you don't know how to get metropolis to behave the same, just ask another question at the metropolis issue tracker. I'm happy to help you over there again.

**Comment by Flo-Wo** [comment]
Okay, thanks
